version: '2'
services:
<<<<<<< HEAD
  moodledb_rpi_alpine:
    image: arm32v7/postgres
    container_name: moodledb_rpi_alpine
    env_file: .env
    environment:
    # MAKE SURE THIS ONE SAME WITH THE MOODLE
    - POSTGRES_DATABASE=$POSTGRES_DATABASE
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  moodle_rpi_alpine:
    image: treehouses/moodle:rpi-alpine-latest
    container_name: moodle_rpi_alpine
    ports:
      - "80:80"
    environment:
    - MOODOLE_DB_URL=moodledb_rpi_alpine
=======
  moodledb_rpi:
    image: arm32v7/postgres:11
    container_name: moodledb_rpi
    environment:
    # MAKE SURE THIS ONE SAME WITH THE MOODLE
    - POSTGRES_DATABASE=moodle
    - POSTGRES_USER=moodle
    - POSTGRES_PASSWORD=moodle
  moodle_rpi:
    image: treehouses/moodle:rpi-latest
    container_name: moodle_rpi
    ports:
      - "80:80"
    environment:
    - NGINX_PORT=80
    - MOODOLE_DB_URL=moodledb_rpi
>>>>>>> f6043bc63b52c94590701cfbdb2d13813503ebab
    - MOODOLE_DB_NAME=moodle
    - MOODOLE_DB_USER=moodle
    - MOODOLE_DB_PASS=moodle
    - MOODOLE_DB_PORT=5432
    - MOODOLE_MAX_BODY_SIZE=200M
<<<<<<< HEAD
    - MOODOLE_BODY_TIMEOUT=300s
=======
    - MOODOLE_BODY_TIMEOUT=300s
>>>>>>> f6043bc63b52c94590701cfbdb2d13813503ebab
